import { APP_VERSION } from "../constants/version.js";
import { SHAREPOINT_KB_CONFIG } from "../constants/categories.js";

/**
 * Convert simple Markdown to HTML (used for Word export & previews)
 */
export function markdownToHtml(md) {
  if (!md) return "";
  return md
    .replace(/^#### (.*$)/gm, '<h4>$1</h4>')
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    .replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/^\|(.+)\|$/gm, (m, row) => '<tr>' + row.split('|').map(c => `<td>${c.trim()}</td>`).join('') + '</tr>')
    .replace(/^>\s?(.*$)/gm, '<blockquote>$1</blockquote>')
    .replace(/^---$/gm, '<hr>')
    .replace(/^\- (.*$)/gm, '<li>$1</li>')
    .replace(/^\d+\.\s(.*$)/gm, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');
}

/**
 * Export markdown content to Microsoft Word (.doc) file via browser download
 */
export function exportToWord(content, title) {
  const htmlBody = markdownToHtml(content);
  const now = new Date().toLocaleDateString("en-SG", { year: "numeric", month: "long", day: "numeric" });
  const html = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset='utf-8'><title>${title}</title>
<!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom></w:WordDocument></xml><![endif]-->
<style>
@page { size: A4; margin: 2.5cm; }
body { font-family: 'Segoe UI', 'Calibri', sans-serif; font-size: 11pt; line-height: 1.6; color: #333; }
h1 { color: #0078D4; font-size: 22pt; border-bottom: 2px solid #0078D4; padding-bottom: 6pt; margin-top: 24pt; }
h2 { color: #005A9E; font-size: 16pt; margin-top: 18pt; border-bottom: 1px solid #E0E0E0; padding-bottom: 4pt; }
h3 { color: #333; font-size: 13pt; margin-top: 14pt; }
h4 { color: #555; font-size: 11pt; margin-top: 10pt; }
code { background: #F5F5F5; padding: 2px 4px; font-family: 'Consolas', 'Courier New', monospace; font-size: 10pt; border: 1px solid #E0E0E0; border-radius: 3px; }
pre { background: #F5F5F5; padding: 12px; font-family: 'Consolas', monospace; font-size: 10pt; border: 1px solid #DDD; border-radius: 4px; white-space: pre-wrap; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; }
th, td { border: 1px solid #DDD; padding: 8px 12px; text-align: left; font-size: 10pt; }
th { background: #0078D4; color: white; font-weight: 600; }
tr:nth-child(even) { background: #F9F9F9; }
blockquote { border-left: 4px solid #0078D4; margin: 12px 0; padding: 8px 16px; background: #F0F6FF; color: #333; }
li { margin-bottom: 4px; }
hr { border: none; border-top: 1px solid #E0E0E0; margin: 16px 0; }
.header-meta { color: #666; font-size: 9pt; margin-bottom: 24pt; border-bottom: 1px solid #E0E0E0; padding-bottom: 8pt; }
.footer { color: #999; font-size: 8pt; text-align: center; margin-top: 40pt; border-top: 1px solid #E0E0E0; padding-top: 8pt; }
</style></head>
<body>
<div class="header-meta">
<strong>VGC Technology Pte Ltd</strong> — IT Service Management<br>
Document: ${title}<br>
Generated: ${now} | Classification: Internal | Version: 1.0<br>
SharePoint: <a href="${SHAREPOINT_KB_CONFIG.helpdeskLibraryUrl}">Helpdesk Document Library</a>
</div>
<p>${htmlBody}</p>
<div class="footer">
Generated by VGC-ITSM AI Knowledge Portal v${APP_VERSION.version} — ${APP_VERSION.engine}<br>
&copy; ${new Date().getFullYear()} VGC Technology Pte Ltd. All rights reserved.
</div>
</body></html>`;
  const blob = new Blob(['\ufeff', html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-')}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}
